"""add ltree

Revision ID: d38f56ea732f
Revises: 6de53eb36a9f
Create Date: 2024-10-25 15:50:29.598925

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d38f56ea732f"
down_revision: Union[str, None] = "6de53eb36a9f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS ltree;")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP EXTENSION IF EXISTS ltree;")
    # ### end Alembic commands ###
