"""add head of department

Revision ID: f91bf7407f7b
Revises: 1373e3317818
Create Date: 2024-11-05 19:25:42.507541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f91bf7407f7b'
down_revision: Union[str, None] = '1373e3317818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('head_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'department', 'user', ['head_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'department', type_='foreignkey')
    op.drop_column('department', 'head_id')
    # ### end Alembic commands ###
